In [1]:
import torch
x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [2]:
x[1]

tensor(2)

In [3]:
x.shape

torch.Size([4])

In [4]:
y= torch.ones_like(x)
y

tensor([1, 1, 1, 1])

In [5]:
y.view(2,2)

tensor([[1, 1],
        [1, 1]])

In [7]:
torch.randn(5,5)

tensor([[-0.3234, -0.5165,  0.8250, -1.0182, -1.4410],
        [-0.2033, -1.7989, -0.6795, -1.0526,  0.2057],
        [ 0.8276,  0.8728, -0.9982, -0.6077, -0.5272],
        [ 0.0385,  1.1109,  0.6574, -0.2209, -0.3214],
        [-1.2290, -0.5040, -1.3702, -1.4027, -1.6107]])